# This file was manually created to act as a model for the program.asm that is generated by the compiler
global _start

section .text
_start:
    mov rax, 60 ; load syscall code for exit
    mov rdi, 42 ; set full 64-bit register.
    syscall